module.exports = {
  // Global
  SET_CANCEL_CALLBACK: 'SET_CANCEL_CALLBACK',
  SET_ENKETO_STATUS: 'SET_ENKETO_STATUS',
  SET_SELECT_MODE: 'SET_SELECT_MODE',
  SET_SELECTED: 'SET_SELECTED',
  UPDATE_SELECTED: 'UPDATE_SELECTED',
  UPDATE_SELECTED_ITEM: 'UPDATE_SELECTED_ITEM',
  SET_FIRST_SELECTED_DOC_PROPERTY: 'SET_FIRST_SELECTED_DOC_PROPERTY',
  SET_FIRST_SELECTED_FORMATTED_PROPERTY: 'SET_FIRST_SELECTED_FORMATTED_PROPERTY',
  ADD_SELECTED_MESSAGE: 'ADD_SELECTED_MESSAGE',
  REMOVE_SELECTED_MESSAGE: 'REMOVE_SELECTED_MESSAGE',
  ADD_SELECTED: 'ADD_SELECTED',
  REMOVE_SELECTED: 'REMOVE_SELECTED',
  SET_LOADING_SELECTED_CHILDREN: 'SET_LOADING_SELECTED_CHILDREN',
  SET_LOADING_SELECTED_REPORTS: 'SET_LOADING_SELECTED_REPORTS',
  RECEIVE_SELECTED_CHILDREN: 'RECEIVE_SELECTED_CHILDREN',
  RECEIVE_SELECTED_REPORTS: 'RECEIVE_SELECTED_REPORTS',
  SET_LOADING_CONTENT: 'SET_LOADING_CONTENT',
  SET_LOADING_SUB_ACTION_BAR: 'SET_LOADING_SUB_ACTION_BAR',
  SET_SHOW_ACTION_BAR: 'SET_SHOW_ACTION_BAR',
  SET_SHOW_CONTENT: 'SET_SHOW_CONTENT',
  SET_FACILITIES: 'SET_FACILITIES',
  SET_VERSION: 'SET_VERSION',

  // Contacts
  SET_LOADING_SUMMARY: 'SET_LOADING_SUMMARY',

  // Messages
  SET_MESSAGES_ERROR: 'SET_MESSAGES_ERROR',

  // Reports
  SET_REPORTS_ERROR_SYNTAX: 'SET_REPORTS_ERROR_SYNTAX'
};
