module.exports = {
  // Global
  CLEAR_SELECTED: 'CLEAR_SELECTED',
  SET_ACTION_BAR_LEFT: 'SET_ACTION_BAR_LEFT',
  SET_ACTION_BAR_RIGHT: 'SET_ACTION_BAR_RIGHT',
  SET_ACTION_BAR_RIGHT_VERIFIED: 'SET_ACTION_BAR_RIGHT_VERIFIED',
  SET_ANDROID_APP_VERSION: 'SET_ANDROID_APP_VERSION',
  SET_CANCEL_CALLBACK: 'SET_CANCEL_CALLBACK',
  SET_CURRENT_TAB: 'SET_CURRENT_TAB',
  SET_ENKETO_STATUS: 'SET_ENKETO_STATUS',
  SET_FILTER: 'SET_FILTER',
  SET_FILTERS: 'SET_FILTERS',
  SET_FORMS: 'SET_FORMS',
  SET_IS_ADMIN: 'SET_IS_ADMIN',
  SET_LOADING_CONTENT: 'SET_LOADING_CONTENT',
  SET_LOADING_SUB_ACTION_BAR: 'SET_LOADING_SUB_ACTION_BAR',
  SET_MINIMAL_TABS: 'SET_MINIMAL_TABS',
  SET_SELECT_MODE: 'SET_SELECT_MODE',
  SET_SHOW_ACTION_BAR: 'SET_SHOW_ACTION_BAR',
  SET_SHOW_CONTENT: 'SET_SHOW_CONTENT',
  SET_TITLE: 'SET_TITLE',
  SET_UNREAD_COUNT: 'SET_UNREAD_COUNT',

  UPDATE_UNREAD_COUNT: 'UPDATE_UNREAD_COUNT',
  UPDATE_REPLICATION_STATUS: 'UPDATE_REPLICATION_STATUS',

  // Analytics
  SET_SELECTED_ANALYTICS: 'SET_SELECTED_ANALYTICS',

  // Contacts
  RECEIVE_SELECTED_CONTACT_CHILDREN: 'RECEIVE_SELECTED_CONTACT_CHILDREN',
  RECEIVE_SELECTED_CONTACT_REPORTS: 'RECEIVE_SELECTED_CONTACT_REPORTS',
  RECEIVE_SELECTED_CONTACT_TARGET_DOC: 'RECEIVE_SELECTED_CONTACT_TARGET_DOC',
  SET_LOADING_SELECTED_CONTACT: 'SET_LOADING_SELECTED_CONTACT',
  SET_CONTACTS_LOADING_SUMMARY: 'SET_CONTACTS_LOADING_SUMMARY',
  SET_SELECTED_CONTACT: 'SET_SELECTED_CONTACT',
  UPDATE_SELECTED_CONTACT: 'UPDATE_SELECTED_CONTACT',
  UPDATE_SELECTED_CONTACT_TASKS: 'UPDATE_SELECTED_CONTACT_TASKS',

  // Messages
  REMOVE_MESSAGE_FROM_SELECTED_CONVERSATION: 'REMOVE_MESSAGE_FROM_SELECTED_CONVERSATION',
  SET_MESSAGES_ERROR: 'SET_MESSAGES_ERROR',
  SET_SELECTED_CONVERSATION: 'SET_SELECTED_CONVERSATION',
  UPDATE_SELECTED_CONVERSATION: 'UPDATE_SELECTED_CONVERSATION',
  SET_CONVERSATIONS: 'SET_CONVERSATIONS',
  MARK_SELECTED_CONVERSATION_READ: 'MARK_SELECTED_CONVERSATION_READ',

  // Reports
  ADD_SELECTED_REPORT: 'ADD_SELECTED_REPORT',
  REMOVE_SELECTED_REPORT: 'REMOVE_SELECTED_REPORT',
  SET_FIRST_SELECTED_REPORT_DOC_PROPERTY: 'SET_FIRST_SELECTED_REPORT_DOC_PROPERTY',
  SET_FIRST_SELECTED_REPORT_FORMATTED_PROPERTY: 'SET_FIRST_SELECTED_REPORT_FORMATTED_PROPERTY',
  SET_SELECTED_REPORTS: 'SET_SELECTED_REPORTS',
  SET_VERIFYING_REPORT: 'SET_VERIFYING_REPORT',
  UPDATE_SELECTED_REPORT_ITEM: 'UPDATE_SELECTED_REPORT_ITEM',

  // Trainings
  ADD_SELECTED_TRAINING: 'ADD_SELECTED_TRAINING',
  REMOVE_SELECTED_TRAINING: 'REMOVE_SELECTED_TRAINING',
  SET_FIRST_SELECTED_TRAINING_DOC_PROPERTY: 'SET_FIRST_SELECTED_TRAINING_DOC_PROPERTY',
  SET_FIRST_SELECTED_TRAINING_FORMATTED_PROPERTY: 'SET_FIRST_SELECTED_TRAINING_FORMATTED_PROPERTY',
  SET_SELECTED_TRAININGS: 'SET_SELECTED_TRAININGS',
  SET_VERIFYING_TRAINING: 'SET_VERIFYING_TRAINING',
  UPDATE_SELECTED_TRAINING_ITEM: 'UPDATE_SELECTED_TRAINING_ITEM',
  
  // Services
  SET_LAST_CHANGED_DOC: 'SET_LAST_CHANGED_DOC',

  // Tasks
  SET_SELECTED_TASK: 'SET_SELECTED_TASK',
  SET_TASKS_LOADED: 'SET_TASKS_LOADED',

  // Target Aggregates
  SET_TARGET_AGGREGATES: 'SET_TARGET_AGGREGATES',
  SET_SELECTED_TARGET_AGGREGATE: 'SET_SELECTED_TARGET_AGGREGATE',
  SET_TARGET_AGGREGATES_ERROR: 'SET_TARGET_AGGREGATES_ERROR',
};
