module.exports = {
  SET_CANCEL_CALLBACK: 'SET_CANCEL_CALLBACK',
  SET_ENKETO_STATUS: 'SET_ENKETO_STATUS',
  SET_SELECT_MODE: 'SET_SELECT_MODE',
  SET_SELECTED: 'SET_SELECTED',
  UPDATE_SELECTED: 'UPDATE_SELECTED',
  UPDATE_SELECTED_ITEM: 'UPDATE_SELECTED_ITEM',
  SET_FIRST_SELECTED_DOC_PROPERTY: 'SET_FIRST_SELECTED_DOC_PROPERTY',
  SET_FIRST_SELECTED_FORMATTED_PROPERTY: 'SET_FIRST_SELECTED_FORMATTED_PROPERTY',
  ADD_SELECTED_MESSAGE: 'ADD_SELECTED_MESSAGE',
  REMOVE_SELECTED_MESSAGE: 'REMOVE_SELECTED_MESSAGE',
  ADD_SELECTED: 'ADD_SELECTED',
  REMOVE_SELECTED: 'REMOVE_SELECTED',
  SET_LOADING_SELECTED_CHILDREN: 'SET_LOADING_SELECTED_CHILDREN',
  SET_LOADING_SELECTED_REPORTS: 'SET_LOADING_SELECTED_REPORTS',
  RECEIVE_SELECTED_CHILDREN: 'RECEIVE_SELECTED_CHILDREN',
  RECEIVE_SELECTED_REPORTS: 'RECEIVE_SELECTED_REPORTS',
  SET_LAST_CHANGED_DOC: 'SET_LAST_CHANGED_DOC'
};
