#!/bin/bash -eu
# we assume that the admin user already exists

delete_doc() {
	echo "[$0] Deleting doc $1"
	local docUrl="$COUCH_URL/$1"
	echo "DOCURL $docUrl"
	local rev="$(curl "$docUrl" | jq --raw-output ._rev)"
	if [[ "$rev" != "null" ]]; then
		curl -X DELETE "$docUrl?rev=$rev"
	fi
}

delete_user() {
	echo "[$0] Deleting user $1"
	local username="$1"
	curl -X DELETE "$API_URL/api/v1/users/$username"
}

echo "[$0] Setting up fixtures for api e2e test. Cleaning up old test data..."

delete_user "bob"
delete_user "clare"
delete_user "chw-boss"
delete_user "chw"

delete_doc "PARENT_PLACE"
delete_doc "fixture:bobville"
delete_doc "fixture:clareville"
delete_doc "fixture:chw-bossville"
delete_doc "fixture:chwville"
delete_doc "fixture:user:chw"
delete_doc "fixture:user:chw-boss"

echo "[$0] Finished cleanup. Creating new test data..."

echo "[$0] creating the PARENT_PLACE..."
curl -X PUT \
	--data '{ "_id":"PARENT_PLACE", "type":"district_hospital", "name":"Big Parent Hospital" }' \
	"$COUCH_URL/PARENT_PLACE"

echo "[$0] creating user: bob..."
curl -X POST \
	-H 'Content-Type: application/json' \
	--data '{
	  "username":"bob",
	  "password":"secret",
	  "place":{
	     "_id":"fixture:bobville",
	     "type":"health_center",
	     "name":"Bobville",
	     "parent":"PARENT_PLACE"
	  },
	  "contact":{
	    "name":"Bob"
	  },
	  "roles":["district-manager", "kujua_user", "data_entry", "district_admin"]
	}' \
	"$API_URL/api/v1/users"

echo "[$0] creating user: clare..."
curl -X POST \
	-H 'Content-Type: application/json' \
	--data '{
	  "username":"clare",
	  "password":"secret",
	  "place":{
	     "_id":"fixture:clareville",
	     "type":"health_center",
	     "name":"Clareville",
	     "parent":"PARENT_PLACE"
	  },
	  "contact":{
	    "name":"Clare"
	  },
	  "roles":[]
	}' \
	"$API_URL/api/v1/users"

echo "[$0] creating user: chw-boss..."
curl -X POST \
	-H 'Content-Type: application/json' \
	--data '{
	  "username":"chw-boss",
	  "password":"secret",
	  "place":{
	     "_id":"fixture:chw-bossville",
	     "type":"health_center",
	     "name":"CHW Bossville",
	     "parent":"PARENT_PLACE"
	  },
	  "contact":{
	    "_id":"fixture:user:chw-boss",
	    "name":"CHW Boss"
	  },
	  "roles":[]
	}' \
	"$API_URL/api/v1/users"

echo "[$0] creating user: chw..."
curl -X POST \
	-H 'Content-Type: application/json' \
	--data '{
	  "username":"chw",
	  "password":"secret",
	  "place":{
	     "_id":"fixture:chwville",
	     "type":"district_hospital",
	     "name":"Chwville",
	     "parent":"fixture:chw-bossville"
	  },
	  "contact":{
	    "_id":"fixture:user:chw",
	    "name":"CHW"
	  },
	  "roles":[]
	}' \
	"$API_URL/api/v1/users"

echo "[$0] Done."

