FROM alpine:3.12.3

RUN apk add --update --no-cache \
  build-base \
  nodejs-current \
  curl \
  npm \
  tzdata \
  libxslt \
  bash \
  jq    \
  git

WORKDIR /app

COPY ./sentinel ./sentinel

RUN cd sentinel && npm ci --verbose
COPY ./shared-libs ./sentinel/node_modules/@medic

ENV NODE_PATH=/app/sentinel/node_modules

ENTRYPOINT ["/bin/bash", "/app/sentinel/docker-entrypoint.sh"]