#!/usr/bin/env bash -eu

strs() {
	grep -o '{{[^}]*}}' "$@" | sort -u
}

cd translations
english_strings="$(strs messages-en.properties)"
bad_trans=false

for tran in *.properties; do
	case $tran in
		*-en.properties) ;;
		*)
			echo "# $tran"
			this="$(strs $tran)"
			extras="$(comm -13 <(echo "$english_strings") <(echo "$this"))"
			if [[ -z "$extras" ]]; then
				echo "# OK"
			else
				echo "# Found bad translations:"
				echo "$extras"
				bad_trans=true
			fi
			echo "# ---"
			;;
	esac
done

echo "Translation check complete."
if $bad_trans; then
	echo "Bad translations."
	exit 1
fi
echo "All good."
