{{- if eq (toString .Values.couchdb.clusteredCouch_enabled) "false" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cht.service: couchdb
  name: cht-couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      cht.service: couchdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        cht.service: couchdb
    spec:
      tolerations:
      - key: {{ .Values.toleration.key }}
        operator: {{ .Values.toleration.operator }}
        value: {{ .Values.toleration.value | quote }}
        effect: {{ .Values.toleration.effect }}
      # Check if .Values.nodes.single_node_deploy has a value
    {{- if hasKey .Values "nodes" }}
      {{- if hasKey .Values.nodes "single_node_deploy" }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodes.single_node_deploy }}
      {{- end }}
    {{- end }}
      containers:
        - env:
            - name: COUCHDB_LOG_LEVEL
              value: info
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cht-couchdb-credentials
                  key: COUCHDB_PASSWORD
            - name: COUCHDB_SECRET
              valueFrom:
                secretKeyRef:
                  name: cht-couchdb-credentials
                  key: COUCHDB_SECRET
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: cht-couchdb-credentials
                  key: COUCHDB_USER
            - name: COUCHDB_UUID
              valueFrom:
                secretKeyRef:
                  name: cht-couchdb-credentials
                  key: COUCHDB_UUID
            - name: SVC_NAME
              value: couchdb.{{ .Values.namespace }}.svc.cluster.local
          image: {{ .Values.upstream_servers.docker_registry }}/cht-couchdb:{{ .Values.cht_image_tag }}
          name: cht-couchdb
          ports:
            - containerPort: 5984
          resources: {}
          {{- if eq (toString .Values.cluster_type) "k3s-k3d" }}
          volumeMounts:
            - mountPath: /opt/couchdb/data
              name: local-volume
              subPath: data
            - mountPath: /opt/couchdb/etc/local.d
              name: local-volume
              subPath: local.d
          {{- else }}
          volumeMounts:
            - mountPath: /opt/couchdb/data
              name: couchdb-claim0
              subPath: data
            - mountPath: /opt/couchdb/etc/local.d
              name: couchdb-claim0
              subPath: local.d
          {{- end }}
      restartPolicy: Always
      {{- if eq (toString .Values.cluster_type) "k3s-k3d" }}
      volumes:
        - name: local-volume
          hostPath:
            path: {{ .Values.local.diskPath }}
      {{- else }}
      volumes:
        - name: couchdb-claim0
          persistentVolumeClaim:
            claimName: couchdb-claim0
      {{- end }}
status: {}
{{- end }}
