apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-servers-configmap
data:
  {{- $root := . -}}
  {{- if $root.Values.couchdb.clusteredCouch_enabled }}
  {{- $servers := list -}}
  {{- range $i, $e := until (int $root.Values.clusteredCouch.noOfCouchDBNodes) }}
  {{- $nodeNumber := add $i 1 }}
  {{- $servers = append $servers (printf "couchdb-%d.%s.svc.cluster.local" $nodeNumber $root.Values.namespace) -}}
  {{- end }}
  COUCHDB_SERVERS: {{ join "," $servers }}
  COUCHDB_SYNC_ADMINS_NODE: couchdb-1.{{ $root.Values.namespace }}.svc.cluster.local
  {{- $ips := list -}}
  {{- range $j, $e := untilStep 1 (int $root.Values.clusteredCouch.noOfCouchDBNodes) 1 }}
  {{- $ips = append $ips (printf "couchdb-%d.%s.svc.cluster.local" (add $j 2) $root.Values.namespace) -}}
  {{- end }}
  CLUSTER_PEER_IPS: {{ join "," $ips }}
  {{- else }}
  COUCHDB_SERVERS: couchdb.{{ $root.Values.namespace }}.svc.cluster.local
  {{- end }}
