name: 'PR Search and Replace'
description: 'Search and replace in the body of a PR'
inputs:
  token:
    description: 'The token to use to access the GitHub API'
    required: true

runs:
  using: 'node20'
  main: './compiled/index.js'
