#!/bin/bash

function usage() {
  echo "Usage: $0 <namespace>"
  echo
  echo "This script saves logs from all pods within the specified namespace into local files and then creates a tar.gz archive of these logs."
  echo
  echo "Arguments:"
  echo "  namespace   - The namespace from which to retrieve and archive pod logs."
  echo
  echo "Example: $0 mynamespace"
  exit 1
}

if [ "$#" -ne 1 ]; then
  usage
fi

NAMESPACE=$1
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
LOG_DIR=$(mktemp -d "${NAMESPACE}-logs_${TIMESTAMP}-XXXXXX")

# Get a list of all pod names in the namespace
PODS=$(kubectl -n $NAMESPACE get pods -o jsonpath="{.items[*].metadata.name}")

if [ -z "$PODS" ]; then
  echo "No Pods found in Namespace $NAMESPACE."
  rm -rf "$LOG_DIR"
  exit 1
fi

# Loop through all pod names and fetch logs, saving them to individual files
for POD in $PODS; do
  kubectl -n $NAMESPACE logs $POD > "$LOG_DIR/$POD.log"
done

# Create a tar.gz archive of the log files
tar -czf "$NAMESPACE-logs_$TIMESTAMP.tar.gz" -C "$LOG_DIR" .
if [ $? -eq 0 ]; then
  echo "Logs archived in $NAMESPACE-logs_$TIMESTAMP.tar.gz"
  rm -rf "$LOG_DIR"
else
  echo "Failed to create archive."
  rm -rf "$LOG_DIR"
  exit 1
fi
