#!/bin/bash

function usage() {
  echo "Usage: $0 <namespace>"
  echo
  echo "This script retrieves the list of deployments for a given namespace."
  echo
  echo "Arguments:"
  echo "  namespace   - The namespace in which the deployments reside."
  echo
  echo "Example: $0 mynamespace"
  exit 1
}

if [ "$#" -ne 1 ]; then
  usage
fi

NAMESPACE=$1

kubectl -n $NAMESPACE get deployments

if [ $? -ne 0 ]; then
  echo "An error occurred while trying to retrieve deployments for namespace $NAMESPACE. Please verify that the namespace exists and that you have permissions to view its contents."
  exit 1
fi
