#!/bin/bash

function usage() {
  echo "Usage: $0 <namespace> <deployment>"
  echo
  echo "This script restarts a given deployment."
  echo "The deployment should be in the form 'cht-<service-name>'."
  echo
  echo "Arguments:"
  echo "  namespace   - The namespace in which the deployment resides."
  echo "  deployment  - The name of the deployment ('cht-<service-name>')."
  echo
  echo "Example: $0 mynamespace cht-couchdb-1"
  exit 1
}

if [ "$#" -ne 2 ]; then
  usage
fi

NAMESPACE=$1
DEPLOYMENT=$2

# Restart the deployment
kubectl -n $NAMESPACE rollout restart deployment/$DEPLOYMENT

# Check if the restart was successful
if [ $? -eq 0 ]; then
  echo "Successfully restarted deployment $DEPLOYMENT in namespace $NAMESPACE."
else
  echo "Failed to restart deployment $DEPLOYMENT in namespace $NAMESPACE."
  exit 1
fi
