#!/bin/bash

function usage() {
  echo "Usage: $0 <namespace> <deployment>"
  echo
  echo "This script retrieves the logs for the first pod of a given deployment."
  echo "The deployment should be in the form 'cht-<service-name>'."
  echo
  echo "Arguments:"
  echo "  namespace   - The namespace in which the deployment resides."
  echo "  deployment  - The name of the deployment ('cht-<service-name>')."
  echo
  echo "Example: $0 mynamespace cht-couchdb-1"
  exit 1
}

if [ "$#" -ne 2 ]; then
  usage
fi

NAMESPACE=$1
DEPLOYMENT=$2
SERVICE=${DEPLOYMENT#cht-}
POD_NAME=$(kubectl -n $NAMESPACE get pods -l cht.service=$SERVICE -o jsonpath="{.items[0].metadata.name}")

if [ -z "$POD_NAME" ]; then
  echo "No Pods found for deployment $DEPLOYMENT in Namespace $NAMESPACE."
  exit 1
fi

kubectl -n $NAMESPACE logs $POD_NAME
