apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cht.service: sentinel
  name: cht-sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      cht.service: sentinel
  strategy: {}
  template:
    metadata:
      labels:
        cht.service: sentinel
    spec:
      containers:
        - env:
            - name: API_HOST
              value: api.{{ .Values.namespace }}.svc.cluster.local
            - name: COUCH_URL
              valueFrom:
                secretKeyRef:
                  name: cht-couchdb-credentials
                  key: COUCH_URL
          image: public.ecr.aws/s5s3h4s7/cht-sentinel:{{ .Values.chtversion }}-{{ .Values.chtversion }}
          name: cht-sentinel
          resources: {}
      restartPolicy: Always
status: {}
