#!/bin/bash -eu

# start couchdb 2.x docker instance
docker run -d -p 5984:5984 --name couch -e COUCHDB_PASSWORD=pass -e COUCHDB_USER=admin medicmobile/cht-couchdb:clustered-test4
echo "Starting CouchDB"
until nc -z localhost 5984; do sleep 1; done
echo "CouchDB Started"
