version: '3.9'

# For more information on how to use this docker compose file see our docs page:
#   https://docs.communityhealthtoolkit.org/apps/guides/hosting/self-hosting/

services:
  couch:
    container_name: couch
    image: couchdb:2.3.1
    working_dir: /srv
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=pass
    networks:
     - e2e
      
  horti:
    container_name: horti
    image: ubuntu:18.04
    ports:
      - "5988:5988"
      - "31337:31337"
    environment:
      - COUCH=http://admin:pass@couch:5984
      - COUCH_URL=http://admin:pass@couch:5984/medic-test
      - COUCH_NODE_NAME=nonode@nohost
      - HORTI_BUILDS_SERVER=$MARKET_URL_READ/$BUILDS_SERVER
      - BUILD=medic:medic:test-$BUILD_NUMBER
      - NODE_VERSION=$NODE
      - TEST_SUITE=integration
      - IS_TAG=$IS_TAG
      - DEFAULT_BUILDS_URL=https://staging.dev.medicmobile.org/_couch/builds
      - INSTALL_LATEST=$INSTALL_LATEST
    depends_on:
      - couch
    command: /horti_entry.sh
    volumes:
     - "./horti_entry.sh:/horti_entry.sh"
     - "../../tests/logs/:/tests/logs/"
     - "../../:/cht-core"
    networks:
     - e2e

networks:
  e2e:
   name: e2e 
