#!/usr/bin/env node
console.log('[npm_version_check]', 'Version:');
require('child_process').exec('npm --version', (err, stdout, stderr) => {
  if(err) throw err;
  console.log(stdout);
  console.error(stderr);
  console.log('[npm_version_check]', 'Finished.');
});
