#!/bin/bash

NAMESPACE=$1

if [ -z "$NAMESPACE" ]; then
    echo "Namespace is required as an argument."
    exit 1
fi

kubectl -n $NAMESPACE get all

kubectl get svc -n $NAMESPACE api -o yaml > api-yaml.yaml

kubectl get svc -n $NAMESPACE upgrade-service -o yaml > upgrade-service-yaml.yaml

kubectl -n $NAMESPACE delete svc api upgrade-service

kubectl rollout restart deploy/upgrade-service -n $NAMESPACE
kubectl rollout restart deploy/cht-api -n $NAMESPACE

# Sleep for 5 seconds to allow the pods to restart
echo "Waiting for pods to restart"
sleep 5

kubectl apply -f ./upgrade-service-yaml.yaml
kubectl apply -f ./api-yaml.yaml

rm ./upgrade-service-yaml.yaml
rm ./api-yaml.yaml
