apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-manager
rules:
- apiGroups:
  - apps
  - ""
  resources:
  - deployments
  - pods
  verbs:
  - get
  - update
  - watch
  - patch
  - list
