version: "3.7"
services:
    cht-nginx:
        container_name: cht-nginx
        build:
            context: .
            target: ${BUILD_TARGET:-test_nginx}
        ports:
            - 80:80
            - 443:443
        volumes:
            - cht-ssl:/root/.acme.sh/
            - ./tests/tests.bats:/app/tests.bats
        depends_on:
            - cht-api
            - haproxy
        networks:
            - cht-net

    cht-api:
        image: mockserver/mockserver
        container_name: cht-api-mock
        command: -serverPort 5988
        environment:
            MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
            MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
        volumes:
        - ./mock-config:/config
        networks:
            - cht-net

    haproxy:
        image: mockserver/mockserver
        container_name: haproxy-mock
        command: -serverPort 5984
        environment:
            MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
            MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
        volumes:
        - ./mock-config:/config
        networks:
            - cht-net

volumes:
    cht-ssl:
        name: cht-ssl
networks:
    cht-net:
        name: cht-net
