import { AfterViewInit, Component, ElementRef, OnDestroy, ViewChild } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { NgIf } from '@angular/common';
import { Subscription } from 'rxjs';
import { CHTDatasourceService } from '@mm-services/cht-datasource.service';
import { PerformanceService } from '@mm-services/performance.service';
import { UiExtensionsService } from '@mm-services/ui-extensions.service';
import { UserContactSummaryService } from '@mm-services/user-contact-summary.service';
import { ToolBarComponent } from '@mm-components/tool-bar/tool-bar.component';
import { ErrorLogComponent } from '@mm-components/error-log/error-log.component';
import { TranslatePipe } from '@ngx-translate/core';

@Component({
  templateUrl: './ui-extensions-tab.component.html',
  imports: [ToolBarComponent, ErrorLogComponent, TranslatePipe, NgIf]
})
export class UiExtensionsTabComponent implements AfterViewInit, OnDestroy {
  @ViewChild('uiElementTab') container!: ElementRef;
  extensionTitle = '';
  extensionType = '';
  loading = true;
  errorStack?: string;
  accentColor?: string;

  private paramSubscription?: Subscription;
  private errorListener?: (event: ErrorEvent | PromiseRejectionEvent) => void;

  constructor(
    private readonly route: ActivatedRoute,
    private readonly chtDatasourceService: CHTDatasourceService,
    private readonly performanceService: PerformanceService,
    private readonly uiExtensionsService: UiExtensionsService,
    private readonly userContactSummaryService: UserContactSummaryService,
  ) {}

  ngAfterViewInit() {
    let currentExtensionId = undefined;
    this.paramSubscription = this.route.params.subscribe(async (params) => {
      if (currentExtensionId === params['id']) {
        return;
      }
      currentExtensionId = params['id'];
      this.unregisterErrorListener();
      this.registerErrorListener(params['id']);
      this.initializeExtension(params['id']);
    });
  }

  ngOnDestroy() {
    this.paramSubscription?.unsubscribe();
    this.unregisterErrorListener();
  }

  /*
  For normal errors in the Angular code, Zone.js catches > routes to Angular's ErrorHandler > calls console.error
  > FeedbackService's override picks it up and writes a feedback doc.
  Errors generated by the UI Extension web components are not handled by Zone.js/ErrorHandler. Instead, we add a
  listener here to call console.error for these errors to ensure a feedback doc is written.
  Though the listener is global (and in theory can catch all errors, not just those thrown by the extension code), the
  Zone.js/ErrorHandler logic captures errors in the Angular space before they propagate to the global listeners. So,
  in practice, we should not write duplicate feedback docs for the same error.
   */
  private registerErrorListener(extensionId: string) {
    this.errorListener = (event: ErrorEvent | PromiseRejectionEvent) => {
      const error = event instanceof PromiseRejectionEvent ? event.reason : event.error ?? event.message;
      console.error(`Error in UI extension: "${extensionId}"`, error);
    };
    globalThis.addEventListener('error', this.errorListener);
    globalThis.addEventListener('unhandledrejection', this.errorListener);
  }

  private unregisterErrorListener() {
    if (this.errorListener) {
      globalThis.removeEventListener('error', this.errorListener);
      globalThis.removeEventListener('unhandledrejection', this.errorListener);
      this.errorListener = undefined;
    }
  }

  private async initializeExtension(extensionId: string) {
    const elementName = `cht-${extensionId.toLowerCase()}`;
    this.loading = true;
    this.errorStack = undefined;
    this.accentColor = undefined;
    this.extensionTitle = '';
    this.extensionType = '';
    if (this.container?.nativeElement) {
      this.container.nativeElement.innerHTML = '';
    }
    const trackRender = this.performanceService.track();
    try {
      const {
        properties: { title, config, accent_color, type },
        Element
      } = await this.uiExtensionsService.getExtension(extensionId);
      this.extensionTitle = title ?? '';
      this.extensionType = type;
      this.accentColor = accent_color;
      if (!customElements.get(elementName)) {
        customElements.define(elementName, Element);
      }
      const element = document.createElement(elementName);

      Object.assign(element, {
        cht: await this.chtDatasourceService.get(),
        inputs: {
          config,
          userContactSummary: (await this.userContactSummaryService.get())?.context,
        },
      });

      this.container.nativeElement.appendChild(element);
    } catch (error) {
      // Note this catch block does not catch errors propagating from the actual web component code. The error
      // listener registered above handles those errors (but intentionally does not set this.errorStack). The
      // web component is responsible for handling the UX of its errors (e.g. showing an error message to the user).
      // This catch block is for handling errors when loading the extension code (e.g. if the extension's .js file
      // does not export an HTMLElement).
      console.error(`Error initializing UI extension: "${extensionId}"`, error);
      this.errorStack = error?.stack;
    } finally {
      this.loading = false;
      await trackRender?.stop({ name: `ui-extension:${extensionId}:render` });
    }
  }
}
