#!/bin/sh -eu

echo "[$0] Preparing to compact all local ddocs..."

databases="$(curl 2>/dev/null "${COUCH_URL}/_all_dbs" | jq -r .[])"

for db in $databases; do
	echo ''
	echo "[$0] $db | view cleanup..."
	curl 2>/dev/null -X POST \
		-H "Content-Type: application/json" \
		"${COUCH_URL}/$db/_view_cleanup"

	ddocs="$(curl 2>/dev/null "${COUCH_URL}/$db"'/_all_docs?limit=11&startkey="_design"&endkey="_design0"' | jq -r .rows[].id)"

	echo "[$0] $db | ddocs: $ddocs"

	[[ -z "$ddocs" ]] || for ddoc in $ddocs; do
		echo "[$0] $db/$ddoc | Compacting..."
		curl 2>/dev/null -X POST \
			-H "Content-Type: application/json" \
			"${COUCH_URL}/$db/_compact/${ddoc:8}"
	done
done

echo "[$0] Compaction complete."
