#!/usr/bin/env node
const moduleManager = require('../tests/protractor/module-manager');

Promise.resolve()
  .then(() => moduleManager.startNodeModule('api'))
  .then(() => moduleManager.startNodeModule('sentinel'));
