#!/usr/bin/env node
const moduleManager = require('../tests/protractor/module-manager');

Promise.all([
  moduleManager.startNodeModule('api', 'Medic API listening on port'),
  moduleManager.startNodeModule('sentinel', 'startup complete.'),
])
  .then(() => console.log('[e2e] ALL SERVICES STARTED.  READY TO RUN TESTS.'));
