#!/usr/bin/env node
const moduleManager = require('../tests/protractor/module-manager');

moduleManager.startNodeModule('api', 'Medic API listening on port');
moduleManager.startNodeModule('sentinel', 'startup complete.');
