#!/bin/bash

couchUrl="$1"

log() {
	echo "[$(date +%H:%M:%S)] [$0] $@"
}

fmt() {
	local size=$1
	if [ $size -ge 1048576 ]; then
		size="$(echo "scale=2;$size/1048576"| bc) MB"
	elif [ $size -ge 1024 ]; then
		size="$(echo "scale=2;$size/1024" | bc) KB"
	else
		size="$size B"
	fi
	echo $size
}

log "Fetching attachment sizes for couch DB at $couchUrl..."

allDocsResponse="$(curl "$couchUrl/_all_docs" 2>/dev/null)"
if [[ "$allDocsResponse" = 'null' ]]; then
	log "Server did not respond with JSON."
	exit 1
fi
if [[ "$(jq .error <<< "$allDocsResponse")" != 'null' ]]; then
	jq . <<< "$allDocsResponse"
	exit 1
fi

docIds="$(echo "$allDocsResponse" | jq -r .rows[].id)"

totalSize='0'

for id in $docIds; do
	log "[$id] Checking _attachments..."
	attachmentsJson="$(curl -s "$couchUrl/$id" | jq ._attachments)"
	if [[ "$attachmentsJson" = "null" ]]; then continue; fi
	log "[$id] has attachments.  Checking sizes..."
	attachments="$(echo "$attachmentsJson" | jq -r keys[])"

	for attachment in $attachments; do
		log "[$id] [$attachment] Getting size..."
		aSize="$(curl --head "$couchUrl/$id/$attachment" 2>/dev/null | grep Content-Length | cut -d' ' -f2-)"
		# strip trailing whitespace
		aSize=${aSize%%[[:space:]]}
		log "[$id] [$attachment] size: $(fmt $aSize)"
		totalSize="$((totalSize + aSize))"
	done
done

log "Total size: $(fmt $totalSize)"
log "Done."
