#!/bin/bash -eu

if [[ -z "${MEDIC_API-}" ]]; then
	MEDIC_API='../api'
fi
if ! [[ -d "${MEDIC_API}" ]]; then
	echo "\`medic-api\` could not be found at: ${MEDIC_API}"
	echo "Please override location with env var MEDIC_API."
	exit 1
fi

cat <<EOF
Only in APP
	Only in \`messages-en.properties\`
========================================
EOF

comm -3 \
	<(cat \
		<(grep -o '{{\s*'"'"'[^'"'"']*'"'"'\s*|\s*translate\s*}}' templates/**/*.html | \
			cut -d: -f2- | \
			sed -E -e 's/{{\s*['"'"'"](.*)['"'"'"].*/\1/') \
		<(grep -Eo "'"'tour\.(\w+\.)*\w+'"'" static/js/modules/tour.js | \
			tr -d "'") \
	| sort -u) \
	<(cut -d= -f1 ${MEDIC_API}/translations/messages-en.properties | \
		# de-escape slashes
		sed -e 's_\\ _ _g' | \
		# trim whitespace
		sed -e 's/ *$//' | \
		sort -u)
