apiVersion: v1
kind: Service
metadata:
  labels:
    cht.service: api
  name: api
spec:
  ports:
    - name: "https"
      port: 5988
      targetPort: 5988
  selector:
    cht.service: api
status:
  loadBalancer: {}
