var updates = require('kujua-sms/updates'),
    lists = require('kujua-sms/lists'),
    logger = require('kujua-utils').logger,
    baseURL = require('duality/core').getBaseURL(),
    appdb = require('duality/core').getDBURL(),
    querystring = require('querystring'),
    jsDump = require('jsDump'),
    fakerequest = require('couch-fakerequest'),
    helpers = require('../../test-helpers/helpers');


var example = {
    sms_message: {
       from: "+13125551212",
       message: '1!TEST!facility',
       sent_timestamp: '01-19-12 18:45',
       sent_to: "+15551212",
       type: "sms_message",
       locale: "en",
       form: "TEST"
    },
    clinic: {
        "_id": "4a6399c98ff78ac7da33b639ed60f458",
        "_rev": "1-0b8990a46b81aa4c5d08c4518add3786",
        "type": "clinic",
        "name": "Example clinic 1",
        "contact": {
            "name": "Sam Jones",
            "phone": "+13125551212"
        },
        "parent": {
            "type": "health_center",
            "contact": {
                "name": "Neal Young",
                "phone": "+17085551212"
            },
            "parent": {
                "type": "district_hospital",
                "contact": {
                    "name": "Bernie Mac",
                    "phone": "+14155551212"
                }
            }
        }
    },
    days_stocked_out: {},
    quantity_dispensed: {}
};

var expected_callback = {
    data: {
        type: "data_record",
        form: "TEST",
        related_entities: {
            clinic: null
        },
        sms_message: example.sms_message,
        from: "+13125551212",
        errors: [{
            code: "missing_fields",
            fields: ["year","month"],
            message: "Missing or invalid fields: year, month."
        }],
        responses: [
          {
            to: "+13125551212",
            message: "Missing or invalid fields: year, month."
          }
        ],
        tasks: [],
        days_stocked_out: example.days_stocked_out,
        quantity_dispensed: example.quantity_dispensed,
        facility_id:"facility"
    }
};


/*
 * STEP 1:
 *
 * Run add_sms and expect a callback to add a clinic to a data record which
 * contains all the information from the SMS.
 **/
exports.test_to_record_missing_fields = function (test) {

    test.expect(7);

    // Data parsed from a gateway POST
    var data = {
        from: '+13125551212',
        message: '1!TEST!facility',
        sent_timestamp: '01-19-12 18:45',
        sent_to: '+15551212'
    };

    // request object generated by duality includes uuid and query.form from
    // rewriter.
    var req = {
        uuid: '14dc3a5aa6',
        method: "POST",
        headers: helpers.headers("url", querystring.stringify(data)),
        body: querystring.stringify(data),
        form: data
    };

    var resp = fakerequest.update(updates.add_sms, data, req);
    
    var resp_body = JSON.parse(resp[1].body);
    
    delete resp_body.callback.data.reported_date;
    
    test.same(
        resp_body.callback.options.path,
        baseURL + "/TEST/data_record/add/facility/%2B13125551212");

    test.same(resp_body.payload.messages[0].message,
        "Missing or invalid fields: year, month.");

    test.same(
        resp_body.callback.data.errors,
        expected_callback.data.errors
    );
    
    test.same(
        resp_body.callback.data.days_stocked_out,
        expected_callback.data.days_stocked_out
    );
    
    test.same(
        resp_body.callback.data.quantity_dispensed,
        expected_callback.data.quantity_dispensed
    );
    
    test.same(
        resp_body.callback.data.sms_message,
        expected_callback.data.sms_message
    );
    
    test.same(
        resp_body.callback.data,
        expected_callback.data
    );
    
    test.done();
};
