#!/bin/bash -eu

# Create couchdb system tables (this has to be done manually on couchdb 2.0)
curl -X PUT 'http://localhost:5984/{_users,_replicator,_global_changes,_metadata,admins,medic-test}'

echo '[medic] creating admin'
curl -X PUT 'http://localhost:5984/_node/_local/_config/admins/admin' -d '"pass"'

echo '[medic] creating admin user'
curl -X POST 'http://admin:pass@localhost:5984/_users' -H "Content-Type: application/json" -d '{"_id": "org.couchdb.user:admin", "name": "admin", "password":"pass", "type":"user", "roles":[]}'

echo '[medic] setting require_valid_user'
curl -X PUT --data '"true"' 'http://admin:pass@localhost:5984/_node/_local/_config/chttpd/require_valid_user'

echo '[medic] setting max_http_request_size'
curl -X PUT --data '"4294967296"' 'http://admin:pass@localhost:5984/_node/_local/_config/httpd/max_http_request_size'
