#!/bin/bash -eu

curl ${UPLOAD_URL}/_couch/builds_testing/medic:medic:test-${TRAVIS_BUILD_NUMBER}?attachments=true -o ddoc.json
if [[ -z "${TRAVIS_TAG}" ]]; then
  RELEASE_NAME=$TRAVIS_TAG
elif [[ -z "${TRAVIS_BRANCH}" ]]; then
  RELEASE_NAME=$TRAVIS_BRANCH
else
  echo "Not a tag or a branch so not publishing"
  exit 0
fi

echo "Publishing $RELEASE_NAME"
sed -i '' 's/"_id":"medic:medic:test-[0-9]*"/"_id":"medic:medic:$RELEASE_NAME/'
