name: Conventional commits
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  lint_pr_title:
    name: Lint PR title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4
        with:
          node-version: 20.11
      - name: Install dependencies
        run: npm ci
      - name: Run
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: npx --no-install commitlint <<< "$TITLE"
