name: Push Helm Charts→Docs Site

on:

  # CHT Core only pushes new tags when we do a release
  push:
    tags:
      - '*'
  # allow this to be run manually in case a change is made outside
  # of a release
  workflow_dispatch:

jobs:
  checkout-repo-upload-chart-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout CHT Core Repo 🛎️
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Setup Pages ⚙️
        id: pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: Upload artifact 📡
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          # Upload just helm charts
          path: './scripts/build/helm-releases'

  copy-artifacts-to-gh-pages:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: checkout-repo-upload-chart-artifacts
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Publish to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5